### ISSUE TITLE
Can we have the tf.saved_model pb models (tensorflow 2)?

### ISSUE THREAD

**Issue by rizwanishaq** [huseinzol05/malaya-speech#12]
As most of the models are saved with tensorflow 1.x is it possible that we have .pb with tf.saved_model pb?

**Comment by huseinzol05** [comment]
Not sure we can convert from frozen graph into tf.saved_model TF2. But I included all trained checkpoints, eg, https://github.com/huseinzol05/malaya-speech/tree/master/pretrained-model/stt/conformer
