### ISSUE TITLE
Can update SD module to adapt to "spectralcluster" latest version?

### ISSUE THREAD

**Issue by ZhaoTTT** [huseinzol05/malaya-speech#13]
Hi, I would like to use the pretrained model of speaker diarization like below:

`malaya_speech.diarization.spectral_cluster(grouped_vad, speaker_vector, min_clusters = 2, max_clusters = 5)`

However, the terminal will give me an error that _p_percentile is not in __init__.py_
After tracing back, I found this is because current malaya-speech is using old version of library [spectralcluster], and it seems [spectralcluster-0.1.0] works fine for malaya-speech. And latest version of this library is [spectralcluster-0.2.4] (pls refer to https://github.com/wq2012/SpectralCluster)

(below screenshot is the place where caused the error)
https://github.com/huseinzol05/malaya-speech/blob/master/malaya_speech/diarization.py
![image](https://user-images.githubusercontent.com/37223385/156158386-b1b4461f-74d9-4b59-9658-cfac234cff4a.png)

Since currently many other models/libraries are using latest version of [spectralcluster], could malaya-speech update it as well? Otherwise I have to reinstall/downgrade  [spectralcluster] everytime using malaya-speech.

Thank you!

**Comment by huseinzol05** [comment]
can you try to pull request for this? Update from my side will be very slow, thanks!

**Comment by huseinzol05** [comment]
Fixed! not yet pushed to PYPI.

**Comment by ZhaoTTT** [comment]
> Fixed! not yet pushed to PYPI.

Thanks a lot for the support! 
So I can just manually replace the diarization.py with the current version in Github-master branch, right? Any other related files are updated?

**Comment by huseinzol05** [comment]
yep, thats all.
