### ISSUE TITLE
any example code about the how to do the quantize?

### ISSUE THREAD

**Issue by tricky61** [huseinzol05/malaya-speech#15]
and the model denifition is written by tf2, and the inference code is tf1.15?

**Comment by huseinzol05** [comment]
most of the code I code in TF 1.15.5, but should no problem to run in TF 2.X, I tested it on 2.4, 2.5 and 2.9.

Quantization process use `from tensorflow.tools.graph_transforms import TransformGraph`, only available on TF 1.15.X, you can found it on any export notebooks, example, https://github.com/huseinzol05/malaya-speech/blob/master/pretrained-model/stt/conformer/export/base-mixed.ipynb, block [43] and [44].
