### ISSUE TITLE
No file named 'base_directory/haqkiem/metadata.csv'

### ISSUE THREAD

**Issue by EdwinKuo1337** [huseinzol05/malaya-speech#16]
While I was preparing ASR audio set, at the prepare-malty-stt-train.ipynb, at line 
df = pd.read_csv(f'{base_directory}/haqkiem/metadata.csv', header = None, sep = '|'
there's no haqkiem folder in my directory, how do I get that?
I have downloaded the files and ran prepare-audiobook-augmentation.ipynb before.

**Comment by huseinzol05** [comment]
Sorry, I cannot share haqkiem dataset, the user only allow to share the trained models, not the dataset.
