### ISSUE TITLE
Noise_reduction.deep_model

### ISSUE THREAD

**Issue by guilhermebernieri** [huseinzol05/malaya-speech#17]
Hi, I can't use malaya_speech.noise_reduction.deep_model(model = 'resnet-unet')

Returns that: RepositoryNotFoundError: 401 Client Error: Repository Not Found for url: https://huggingface.co/huseinzol05/noise-reduction-resnet-unet/resolve/main/model.pb. If the repo is private, make sure you are authenticated. (Request ID: 0MZtnpOaTpwQd6jIfo3tt)

Can someone help me?

Thanks.

**Comment by huseinzol05** [comment]
migration issue between backblaze and huggingface, to fix it, try https://malaya-speech.readthedocs.io/en/latest/huggingface-repository.html#Load-model-from-Backblaze

Will migrate ASAP.

**Comment by huseinzol05** [comment]
```
malaya_speech.noise_reduction.deep_model(model = 'resnet-unet')
```

Solved.
