### ISSUE TITLE
Each run of greedy_decode may generate different result

### ISSUE THREAD

**Issue by Beast-Leon** [huseinzol05/malaya-speech#18]
Hello, hope you are doing good. I tried to use malaya_speech on a call in singlish, but found out each run may generate different result. Sometimes it will generate the correct full transcript, but sometimes it can't produce anything. Do you have any comments on this? Thanks.

**Code:
con_model = malaya_speech.stt.deep_transducer(model = 'large-conformer-singlish')
samp_audio = librosa.load(<file_path>, sr = 8000)
samp_audio = librosa.resample(samp_audio, orig_sr = 8000, target_sr = 16000)
result = con_model.greedy_decoder([samp_audio])**

**Comment by Beast-Leon** [comment]
Link: https://github.com/Beast-Leon/RandomStuff

Hi, thanks for your quick response. I have attached the link to the jupyter notebook and the audio. Basically each run will generate a different result, appreciate it if you can give it a look.

**Comment by Beast-Leon** [comment]
```
import malaya_speech
import malaya_speech.train.model.conformer as conformer
import malaya_speech.train.model.transducer as transducer
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
import json
import malaya_speech
from malaya_speech.utils import (
    check_file,
    load_graph,
    generate_session,
    nodes_session,
)
from malaya_speech.utils.tf_featurization import STTFeaturizer

y, _ = malaya_speech.load(<audio_file>)
g = malaya_speech.load_graph('output-large-singlish-conformer/frozen_model.pb')
featurizer = STTFeaturizer(normalize_per_feature=True)
inputs = [
    'X_placeholder',
    'X_len_placeholder',
    'encoded_placeholder',
    'predicted_placeholder',
    'states_placeholder',
]
outputs = [
    'encoded',
    'ytu',
    'new_states',
    'padded_features',
    'padded_lens',
    'initial_states',
    'greedy_decoder',
    'non_blank_transcript',
    'non_blank_stime',
]
input_nodes, output_nodes = nodes_session(g, inputs, outputs)
#sess = generate_session(graph = g)
with g.as_default() as g:
   tf.random.set_random_seed(10)
   for i in range(5):
       with generate_session(graph = g) as sess:
           transducer_model = Transducer(
                                     input_nodes,
                                     output_nodes,
                                     featurizer,
                                     vocab,
                                     time_reduction_factor,
                                     sess,
                                     'large-conformer-singlish',
                                     'speech-to-text-transducer',
                                     wavs = [random_wav1, random_wav2, random_wav3],
                                     dummy_sentences = dummy_sentences,
                                     stack = False                  
                                     )
       cur_sentence = transducer_model.greedy_decoder([y])
       print(cur_sentence)
```
From the above code, I am trying to set a graph-level seed to see if I can reproduce same result each time, but it seems the result is still different in each for loop. And I also happen to see the graph have some randomization happening, is the different result each time because of that?

```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
with tf.io.gfile.GFile('output-large-singlish-conformer/frozen_model.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
with tf.Graph().as_default() as graph:
    tf.import_graph_def(graph_def)
graph.get_operations()[49:54]
```
Result:
```
[<tf.Operation 'import/while/random_normal/mean' type=Const>,
 <tf.Operation 'import/while/random_normal/stddev' type=Const>,
 <tf.Operation 'import/while/random_normal/RandomStandardNormal' type=RandomStandardNormal>,
 <tf.Operation 'import/while/random_normal/mul' type=Mul>,
 <tf.Operation 'import/while/random_normal' type=Add>]
```
Appreciate if you can have a look. Thanks!

**Comment by huseinzol05** [comment]
nothing much can do about this, some of the operations inside TF are non-deterministic, eg, https://github.com/tensorflow/tensorflow/issues/3103

**Comment by Beast-Leon** [comment]
> 



> tried,
> 
> ```
> import malaya_speech
> con_model = malaya_speech.stt.deep_transducer(model = 'large-conformer-singlish')
> y, _ = malaya_speech.load('speech/singlish/singlish0.wav')
> con_model.greedy_decoder([samp_audio])
> ```
> 
> returned a result for me. is it really got voice activities inside the audio? Or you can try to use malaya_speech super resolution first to get, 8k -> 44k -> malaya noise reduction -> 16k -> conformer.

Hi, sorry for not trying this method first. But I just tried it and it seems to produce more reproducible results each time. So does it mean we can generate more reproducible results with clearer audios?

**Comment by huseinzol05** [comment]
Of course.
