### ISSUE TITLE
How does the Semisupervised malay dataset do vad?

### ISSUE THREAD

**Issue by 283258771** [huseinzol05/malaya-speech#19]
Hello, may I ask how to do vad for this dataset? You say you use google vad to segment audio, could you please share the link of google vad?

**Comment by huseinzol05** [comment]
https://github.com/huseinzol05/malaya-speech/blob/master/data/semisupervised-malay/semisupervised-googlespeech.py, https://github.com/wiseman/py-webrtcvad
