### ISSUE TITLE
Retraining of Singlish-Large-Conformer

### ISSUE THREAD

**Issue by mr-coconut** [huseinzol05/malaya-speech#20]
Hi~~~
I am trying to understand the code provided in the repo about how to retrain the conformer model. I am wondering if it is possible to retrain the model from a TensorFlow checkpoint and do you have any tutorial code for it? I am new to TensorFlow and found it hard to grasp the whole idea of how to retrain the model. Thanks so much!

**Comment by huseinzol05** [comment]
Pretrained checkpoints at https://github.com/huseinzol05/malaya-speech/tree/master/pretrained-model/stt/conformer, for large singlish conformer is no 24.

Training script at https://github.com/huseinzol05/malaya-speech/blob/master/pretrained-model/stt/conformer/large-singlish.py, to load specific checkpoint, you can follow https://github.com/huseinzol05/malaya-speech/blob/master/pretrained-model/stt/conformer/base.py#L340, from line no 340-348, all this you can read more about Tensorflow Estimator, https://www.tensorflow.org/guide/estimator

My code heavily use Tensorflow 1, you might want upgrade to Tensorflow 2.
