### ISSUE TITLE
Migration Large-Singlish-Conformer pretrained checkpoint from TF1 to TF2

### ISSUE THREAD

**Issue by mr-coconut** [huseinzol05/malaya-speech#22]
Hi~~
Given the current Large-Singlish-Conformer pretrained checkpoint is written in TF1, and the model LSTM path has changed in TF2, I tried to rewrite the checkpoint variable name paths related to LSTM. We can use TF2 to restore the new checkpoint. I attached the colab link below. Feel free to read it. 

https://colab.research.google.com/drive/1AtiC5rz7ZzMMtXfKmcMKA7mHZZWMVvkW?usp=sharing

**Comment by huseinzol05** [comment]
noicaaaahhhhhhhh
