### ISSUE TITLE
Need some help in convert-asr-to-tflite

### ISSUE THREAD

**Issue by Ajay031998** [huseinzol05/malaya-speech#25]
Hello @huseinzol05 ,
first of all thank you for work you are doing in Malaya-Speech. I am working using Malaya-Specch and facing some problems can you please help me to solve these-
1. In "**convert-asr-to-tflite.ipynb**" notebook for downloading vocab following url is giving 404 error."https://raw.githubusercontent.com/huseinzol05/malaya-speech/master/session/prepare-asr/malaya-speech-sst-vocab.json"  also some of the functions of this notebook are not working in tf2 version. please guide.
2. i am working on using ASR Conformer model for mobile devices. please help me for convert **Conformer model into tflite**.
Hoping to hear from you soon.

**Comment by huseinzol05** [comment]
The model not able to convert to tflite because i do looping outside TF graph, so sorry.
