### ISSUE TITLE
There is no spectral_cluster

### ISSUE THREAD

**Issue by codeHorasan** [huseinzol05/malaya-speech#26]
I've been trying to apply this example 
https://github.com/huseinzol05/malaya-speech/blob/master/example/diarization/load-diarization.ipynb

but due to the lack of malaya_speech.diarization.spectral_cluster, I couldn't do it.

**Comment by huseinzol05** [comment]
That notebook is no longer been used, read stable doc at https://malaya-speech.readthedocs.io/en/stable/load-diarization-clustering.html#Spectral-Clustering
