### ISSUE TITLE
Error while loading the model

### ISSUE THREAD

**Issue by gowthambg20** [huseinzol05/malaya-speech#28]
Hi im trying to load the model using the line below it throws me some bugs from because of librosa's mel function

TypeError                                 Traceback (most recent call last)
[<ipython-input-6-81773a3f6301>](https://localhost:8080/#) in <cell line: 1>()
----> 1 speakernet = malaya_speech.speaker_change.deep_model('speakernet')

3 frames
[/usr/local/lib/python3.9/dist-packages/malaya_speech/utils/featurization.py](https://localhost:8080/#) in __init__(self, sample_rate, frame_ms, stride_ms, n_fft, num_feature_bins, preemphasis, normalize_signal, normalize_feature, **kwargs)
     36         self.normalize_feature = normalize_feature
     37 
---> 38         self.mel_basis = librosa.filters.mel(
     39             sr=self.sample_rate,
     40             n_fft=self.n_fft,

TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given

**Comment by huseinzol05** [comment]
What is your malaya-speech version and librosa, I might used deprecated interface.
