### ISSUE TITLE
Quantized models raises an error

### ISSUE THREAD

**Issue by hmtkvs** [huseinzol05/malaya-speech#4]
when I run quantized models I receive the error below:

InvalidArgumentError                      Traceback (most recent call last)
<timed exec> in <module>

~\miniconda3\envs\voice\lib\site-packages\malaya_speech\pipeline\__init__.py in __call__(self, x)
    190 
    191     def __call__(self, x):
--> 192         return self.emit(x)
    193 
    194 

~\miniconda3\envs\voice\lib\site-packages\malaya_speech\pipeline\__init__.py in emit(self, x)
    185 
    186     def emit(self, x):
--> 187         result = self._emit(x)
    188         self.checkpoint.pop('Pipeline', None)
    189         return self.checkpoint

~\miniconda3\envs\voice\lib\site-packages\malaya_speech\pipeline\__init__.py in _emit(self, x)
    149         result = []
    150         for downstream in list(self.downstreams):
--> 151             r = downstream.update(x, who = self)
    152             if type(r) is list:
    153                 result.extend(r)

~\miniconda3\envs\voice\lib\site-packages\malaya_speech\pipeline\__init__.py in update(self, x, who)
    222             raise
    223         else:
--> 224             return self._emit(result)
    225 
    226 

~\miniconda3\envs\voice\lib\site-packages\malaya_speech\pipeline\__init__.py in _emit(self, x)
    149         result = []
    150         for downstream in list(self.downstreams):
--> 151             r = downstream.update(x, who = self)
    152             if type(r) is list:
    153                 result.extend(r)

~\miniconda3\envs\voice\lib\site-packages\malaya_speech\pipeline\__init__.py in update(self, x, who)
    251             index = min(i + self.n, len(x))
    252             result.append(x[i:index])
--> 253         return self._emit(tuple(result))
    254 
    255 

~\miniconda3\envs\voice\lib\site-packages\malaya_speech\pipeline\__init__.py in _emit(self, x)
    149         result = []
    150         for downstream in list(self.downstreams):
--> 151             r = downstream.update(x, who = self)
    152             if type(r) is list:
    153                 result.extend(r)

~\miniconda3\envs\voice\lib\site-packages\malaya_speech\pipeline\__init__.py in update(self, x, who)
    432                 )
    433             if self.method == 'sync':
--> 434                 result = [self.func(e, *self.args, **self.kwargs) for e in x]
    435         except Exception as e:
    436             logger.exception(e)

~\miniconda3\envs\voice\lib\site-packages\malaya_speech\pipeline\__init__.py in <listcomp>(.0)
    432                 )
    433             if self.method == 'sync':
--> 434                 result = [self.func(e, *self.args, **self.kwargs) for e in x]
    435         except Exception as e:
    436             logger.exception(e)

~\miniconda3\envs\voice\lib\site-packages\malaya_speech\model\tf.py in predict(self, inputs)
    236             returned [B].
    237         """
--> 238         probs = np.argmax(self.predict_proba(inputs), axis = 1)
    239         return [self.labels[p] for p in probs]
    240 

~\miniconda3\envs\voice\lib\site-packages\malaya_speech\model\tf.py in predict_proba(self, inputs)
    220         inputs = np.expand_dims(inputs, -1)
    221 
--> 222         return self._sess.run(self._logits, feed_dict = {self._X: inputs})
    223 
    224     def predict(self, inputs):

~\miniconda3\envs\voice\lib\site-packages\tensorflow_core\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    954     try:
    955       result = self._run(None, fetches, feed_dict, options_ptr,
--> 956                          run_metadata_ptr)
    957       if run_metadata:
    958         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~\miniconda3\envs\voice\lib\site-packages\tensorflow_core\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1178     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1179       results = self._do_run(handle, final_targets, final_fetches,
-> 1180                              feed_dict_tensor, options, run_metadata)
   1181     else:
   1182       results = []

~\miniconda3\envs\voice\lib\site-packages\tensorflow_core\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1357     if handle is None:
   1358       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1359                            run_metadata)
   1360     else:
   1361       return self._do_call(_prun_fn, handle, feeds, fetches)

~\miniconda3\envs\voice\lib\site-packages\tensorflow_core\python\client\session.py in _do_call(self, fn, *args)
   1382                     '\nsession_config.graph_options.rewrite_options.'
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385 
   1386   def _extend_graph(self):

InvalidArgumentError: No OpKernel was registered to support Op 'Dequantize' used by node import/prediction/kernel (defined at C:\Users\hmtkv\miniconda3\envs\voice\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) with these attrs: [mode="MIN_FIRST", T=DT_QUINT8]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

	 [[import/prediction/kernel]]

I wonder what might be the reason for this. Thanks in advance

**Comment by huseinzol05** [comment]
What is your Tensorflow version? should be good if Tensorflow version >= 1.15.4
