### ISSUE TITLE
Error When Load Vocoder Model..

### ISSUE THREAD

**Issue by FsalKml** [huseinzol05/malaya-speech#5]
When I load vocoder model :
vocoder_male = malaya_speech.vocoder.melgan(model = 'male') 

I receive the error below :

DecodeError                               Traceback (most recent call last)
c:\users\user\appdata\local\programs\python\python37\lib\site-packages\malaya_speech\utils\__init__.py in load_graph(frozen_graph_filename, **kwargs)
     83             graph_def = tf.compat.v1.GraphDef()
---> 84             graph_def.ParseFromString(f.read())
     85         except Exception as e:

DecodeError: Error parsing message

During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
<ipython-input-36-e22b429d9604> in <module>
----> 1 vocoder_male = malaya_speech.vocoder.melgan(model = 'male')

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\herpetologist\__init__.py in check(*args, **kwargs)
     98                 nested_check(v, p)
     99 
--> 100         return func(*args, **kwargs)
    101 
    102     return check

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\malaya_speech\vocoder.py in melgan(model, quantized, **kwargs)
    111         module = 'vocoder-melgan',
    112         quantized = quantized,
--> 113         **kwargs
    114     )
    115 

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\malaya_speech\supervised\vocoder.py in load(model, module, quantized, **kwargs)
     17         **kwargs,
     18     )
---> 19     g = load_graph(path['model'], **kwargs)
     20 
     21     inputs = ['Placeholder']

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\malaya_speech\utils\__init__.py in load_graph(frozen_graph_filename, **kwargs)
     84             graph_def.ParseFromString(f.read())
     85         except Exception as e:
---> 86             path = frozen_graph_filename.split('Malaya-Speech/')[1]
     87             path = '/'.join(path.split('/')[:-1])
     88             raise Exception(

IndexError: list index out of range

I wonder what's wrong, can you help me. Thank You.

**Comment by huseinzol05** [comment]
Can I know what is your OS and Python version? Cannot replicate the error in google colab, https://colab.research.google.com/drive/1BmpWIQWx1CNz7XvFXEZyboCfbCkP11_j?usp=sharing

**Comment by FsalKml** [comment]
I use Windows 10 and Python version 3.7.9.

**Comment by huseinzol05** [comment]
Herm, I need to find Windows machine asap to solve this problem.
