### ISSUE TITLE
The link of Universal MelGAN tar.gz seems to be missed, could you so kind to provide it?  XD

### ISSUE THREAD

**Issue by Liofang** [huseinzol05/malaya-speech#6]
The link of Universal MelGAN tar.gz seems to be missed, could you so kind to provide it?  XD

**Comment by huseinzol05** [comment]
Oh really? wait, let me check

**Comment by huseinzol05** [comment]
I only able to fix link to universal melgan 1024, https://github.com/huseinzol05/malaya-speech/tree/master/pretrained-model/vocoder/universal-melgan, holy shit, not sure where I put the original Universal Melgan checkpoint, but I do have frozen model for original Universal Melgan.
