### ISSUE TITLE
Have installed malaya but still having the ImportError

### ISSUE THREAD

**Issue by MaisarahPauzi** [huseinzol05/malaya-speech#9]
Hi, I want to use the text to speech function but having this error, but I have installed the malaya package already.

The code:
`female = malaya_speech.tts.fastspeech2(model = 'female')`

The error message:
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/malaya_speech/tts.py in load_text_ids(pad_to, understand_punct, true_case, quantized, **kwargs)
    205     try:
--> 206         import malaya
    207     except BaseException:

5 frames
ImportError: cannot import name 'nx' from 'networkx' (/usr/local/lib/python3.7/dist-packages/networkx/__init__.py)

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/malaya_speech/tts.py in load_text_ids(pad_to, understand_punct, true_case, quantized, **kwargs)
    207     except BaseException:
    208         raise ModuleNotFoundError(
--> 209             'malaya not installed. Please install it by `pip install malaya` and try again.'
    210         )
    211 

ModuleNotFoundError: malaya not installed. Please install it by `pip install malaya` and try again.

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.`

**Comment by huseinzol05** [comment]
networkx released new version, https://pypi.org/project/networkx/#history, use old version, <= 2.5.1
